name : CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install kitefoil
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run tests
        run: |
          python -m unittest tests
